controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001 
    min_x_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    odom_topic: /bumperbot_controller/odom
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["general_goal_checker"]
    progress_checker_plugin: "progress_checker"
  
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    FollowPath:
      plugin: "bumperbot_motion::PDMotionPlanner"
      kp: 2.0
      kd: 0.1
      max_linear_velocity: 0.3
      max_angular_velocity: 1.0
      step_size: 0.2
      
      
local_costmap:
  local_costmap:
    ros__parameters: 
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom 
      robot_base_frame: base_link
      use_sim_time: true
      robot_radius: 0.1
      resolution: 0.05
      always_send_full_costmap: true
      track_unknown_space: true
      rolling_window: true
      width: 3
      height: 3

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          combination_method: 1 # 1 uses max value for each cell. 
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55 
        cost_scaling_factor: 3.0


        




