scan_to_scan_filter_chain:
  ros__parameters:
    scan_filter_chain:
      - name: range_filter
        type: laser_filters/LaserScanRangeFilter
        params:
          use_message_range_limits: false
          lower_threshold: 0.2
          upper_threshold: 5.0
          lower_replacement_value: .nan
          upper_replacement_value: .nan
      - name: intensity_filter
        type: laser_filters/LaserScanIntensityFilter
        params:
          lower_threshold: 30.0
          upper_threshold: 100.0
          disp_histogram: false